### ISSUE TITLE
[1.12][0.4.2.27] Crash with MalisisCore on Server Launch

### ISSUE THREAD

**Issue by Kris1432** [asiekierka/CharsetMC#150]
Forge: 2420
Version: 0.4.2.27

Cause: Server Launch

Crashlog: https://pastebin.com/Xup4in7K

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/issues/118

We had this error already before, and I thought it had been fixed?

**Comment by exaskye** [comment]
It was; looks like it got re-broken.

**Comment by asiekierka** [comment]
@Ordinastie Any ideas?

**Comment by Ordinastie** [comment]
Is there a reason why you can't just ignore that one ?
Anyway, at this point, I wonder if you're not just better off filtering doors with class names not containing "malisis".

**Comment by asiekierka** [comment]
@Ordinastie Are you sure no other mod will encounter this, though? Better off fixing it on your side, especially as you seem to know what the problem is -> https://github.com/CharsetMC/Charset/issues/118

**Comment by Ordinastie** [comment]
It's a bit hard to adapt to other mods reflectively access your classes. You say don't have a choice, but you have to concede it's a pretty dangerous operation.
It also limits the uses of lambdas with client side classes.
I could remove my lambda again, but that just means it will break in a future version when I forget this issue (like I did already with 1.12).
That's why I suggest you filter it out yourself. It most likely safer that way.
