### ISSUE TITLE
Charset Storage Chests do not show up in creative search

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/CharsetMC#253]
Minor nitpick.

It also seems to extend to JEI.

**Comment by asiekierka** [comment]
Chests only show up if a recipe exists for crafting them. Same goes for Barrels. Does any such recipe exist?

By default, they will show a single random (changes daily for variety) Chest variant in the creative search and JEI - this can be changed to show all variants in config/charset/module/lib.cfg. I want to make it so that all Chest variants are always shown in JEI, but havne't gotten around to it.

**Comment by asiekierka** [comment]
The solution I mentioned will most likely have to wait for a JEI API upgrade.

**Comment by asiekierka** [comment]
@Sunconure11 The default behaviour as of 0.5.2.3 is to show all chests, barrels, etc. in JEI, but not in the creative menu. I'll see about adding more configuration options (possibly separate creative tabs? Sub-tabs? ???) later

**Comment by asiekierka** [comment]
Could you please test with Charset 0.5.4.2?
