### ISSUE TITLE
[Transport - Carts and Rails] Incompatibility with Immersive Engineering shaders

### ISSUE THREAD

**Issue by Azmalent** [asiekierka/CharsetMC#353]
Immersive Engineering shaders can't be applied to minecarts when Carts and Rails module is installed.

**Comment by asiekierka** [comment]
Yes. This is due to two reasons:

* ImmersiveEngineering checks if the overridden ModelBase is instanceof ModelMinecart, which ours _is not_ - this is a bug on my side,
* ImmersiveEngineering will never delegate to the wrapped ModelMinecart correctly - this is a bug on BluSunrize's side.

In other words, once I fix this on my side, you need to report back to Blu and state that colors can no longer be applied, as that is what is most likely to happen.

**Comment by asiekierka** [comment]
Test with http://asie.pl/files/Charset-TransportCartsRails-0.5.5.5-IE.jar , please!

**Comment by asiekierka** [comment]
Closed due to lack of activity.
